In [1]:
# Importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
# Loading the datset
Dataset1=pd.read_csv("E:\\Gladys\\DataSets\\iris.csv")

In [3]:
# First five rows of the dataset
Dataset1.head()

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [4]:
# Number of rows and columns in the dataset
Dataset1.shape

(150, 5)

In [5]:
# Overall information of the dataset
Dataset1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   sepallength  150 non-null    float64
 1   sepalwidth   150 non-null    float64
 2   petallength  150 non-null    float64
 3   petalwidth   150 non-null    float64
 4   class        150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [6]:
# Statistically describing the dataset
Dataset1.describe()

sepallength  sepalwidth  petallength  petalwidth
count   150.000000  150.000000   150.000000  150.000000
mean      5.843333    3.054000     3.758667    1.198667
std       0.828066    0.433594     1.764420    0.763161
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.350000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000

In [8]:
# Checking for null values
Dataset1.isnull().sum()

sepallength    0
sepalwidth     0
petallength    0
petalwidth     0
class          0
dtype: int64

In [13]:
# Independent and dependent variables
x=Dataset1.drop(['class'],axis=1)
y=Dataset1['class']

In [15]:
# Feature scaling using MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
MMS=MinMaxScaler()
Scaled_x=MMS.fit_transform(x)
Scaled_x

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [16]:
# splitting the dataset into train and test dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(Scaled_x,y,test_size=0.3,random_state=10)

In [17]:
# Fitting into Gaussian Naive Bayes Classifier
from sklearn.naive_bayes import GaussianNB
GNB=GaussianNB()
GNB.fit(x_train,y_train)
y_pred = GNB.predict(x_test)

In [18]:
# Predicted values
y_pred

array(['Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor'], dtype='<U15')

In [19]:
# Test values
y_test

87     Iris-versicolor
111     Iris-virginica
10         Iris-setosa
91     Iris-versicolor
49         Iris-setosa
60     Iris-versicolor
72     Iris-versicolor
67     Iris-versicolor
39         Iris-setosa
55     Iris-versicolor
66     Iris-versicolor
142     Iris-virginica
53     Iris-versicolor
1          Iris-setosa
19         Iris-setosa
112     Iris-virginica
85     Iris-versicolor
38         Iris-setosa
21         Iris-setosa
35         Iris-setosa
102     Iris-virginica
132     Iris-virginica
126     Iris-virginica
24         Iris-setosa
61     Iris-versicolor
2          Iris-setosa
95     Iris-versicolor
90     Iris-versicolor
76     Iris-versicolor
117     Iris-virginica
58     Iris-versicolor
97     Iris-versicolor
129     Iris-virginica
114     Iris-virginica
146     Iris-virginica
47         Iris-setosa
124     Iris-virginica
120     Iris-virginica
118     Iris-virginica
141     Iris-virginica
26         Iris-setosa
43         Iris-setosa
59     Iris-versicolor
41         

In [21]:
# Confusion matrix
import sklearn.metrics
Label=['Iris-versicolor','Iris-setosa','Iris-virginica']
print(sklearn.metrics.confusion_matrix(y_test,y_pred,labels=Label))

[[17  0  0]
 [ 0 14  0]
 [ 0  0 14]]
